version: "3.8"

services:
  rabbitmq:
    image: 'rabbitmq:3.13-management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - mima-network

  backend:
    build:
      context: ./JavaSpringBoot/projetoMima
      dockerfile: Dockerfile
    container_name: mimastore-backend
    restart: always
    depends_on:
      - rabbitmq
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mimastore-db:3306/MimaStore
      SPRING_DATASOURCE_USERNAME: mimastore_user
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: myuser
      SPRING_RABBITMQ_PASSWORD: secret
    networks:
      - mima-network

networks:
  mima-network:
    external: true
